name: Deploy to Container App from API2

on:
  push:
    branches: ["main"]
    paths: ["Node/API2/**"]
  workflow_dispatch:

env:
  NODE_VERSION: "20.x"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # For Linux, use ubuntu-latest
    environment: dev
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTAINER_KEY }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/Node/API2
          acrName: jacobsteinregistry
          containerAppName: assignment-2-jacob-stein
          resourceGroup: bu2024-519
          environmentVariables: >
            SECRET_3=secretref:secret3
            AzureWebJobsQUEUE_ACCESS_KEY=secretref:azure-web-jobs-queue-access-key
            AzureWebJobsStorage=secretref:azure-web-jobs-storage
            COMPUTER_VISION_KEY=secretref:computer-vision-key
            COMPUTER_VISION_ENDPOINT=secretref:computer-vision-endpoint
            CONTAINER_URL=secretref:container-url
            COSMOS_DB_CONNECTION_STRING=secretref:cosmos-db-connection-string
